#
# Github benchmark test workflow
#
name: CI Benchmark Test
on: [pull_request]
jobs:
  benchmark:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby:
          - '3.2.0'
    services:
      redis:
        image: redis
        ports: ["6379:6379"]
    steps:
    - uses: actions/checkout@v4
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - name: Start redis cluster
      run: bin/cluster start
    - name: Create redis cluster
      run: bin/cluster create -f
    - name: Run benchmark tests
      run: bundle exec ruby benchmark.rb
      env:
        WORKFLOW_PORT: 30001
    - name: Stop redis cluster
      run: bin/cluster stop
    - name: Clean redis cluster
      run: bin/cluster clean
