#
# Github benchmark test workflow
#
name: CI Benchmark Test
on: [pull_request]
permissions:
  contents: read
jobs:
  benchmark:
    runs-on: ubuntu-24.04
    timeout-minutes: 15
    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
    - uses: ruby/setup-ruby@95ef2b042f9d7a56d8268cba8559e2842e2ad01b # v1
      with:
        ruby-version: '3.4'
        bundler-cache: true
    - name: Install redis
      run: sudo apt-get install -y redis-tools redis-server

    - name: Verify that redis is up
      run: redis-cli ping

    - name: Shut primary redis down
      run: sudo systemctl stop redis

    - name: Start redis cluster
      run: bin/cluster start

    - name: Create redis cluster
      run: bin/cluster create -f

    - name: Run benchmark tests
      run: bundle exec ruby benchmark.rb
      env:
        REDIS_PORT: 30001

    - name: Stop redis cluster
      if: always()
      run: bin/cluster stop

    - name: Clean redis cluster
      if: always()
      run: bin/cluster clean
