#
# Github ruby gem build workflow
#
name: CI Ruby Gem Build
on: [pull_request]
jobs:
  release-please:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby:
          - '3.2.0'
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - run: gem build *.gemspec
#      - name: publish gem
#        run: |
#          mkdir -p $HOME/.gem
#          touch $HOME/.gem/credentials
#          chmod 0600 $HOME/.gem/credentials
#          printf -- "---\n:rubygems_api_key: ${GEM_HOST_API_KEY}\n" > $HOME/.gem/credentials
#          gem push *.gem
#        env:
#          GEM_HOST_API_KEY: ${{ secrets.RUBYGEMS_AUTH_TOKEN }}
