#
# Github rspec unit test workflow
#
name: CI RSpec Tests
on: [pull_request]
jobs:
  rspec:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby:
          - '3.3.6'
    services:
      redis:
        image: redis
        ports: ["6379:6379"]
    steps:
    - uses: actions/checkout@v4
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - name: Run unit tests
      run: bundle exec rspec
