#
# Github rubocop linting workflow
#
name: CI Rubocop Linting
on: [pull_request]
jobs:
  rubocop:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby:
          - '3.2.0'
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Rubocop Linter Action
        run: |
          bundle exec rubocop \
            --parallel \
            --fail-level convention \
            --display-only-fail-level-offenses \
            --display-style-guide \
            --force-exclusion \
            --format progress \
            --format github
