#
# Github rubocop linting workflow
#
name: CI Rubocop Linting
on: [pull_request]
permissions:
  contents: read
jobs:
  rubocop:
    runs-on: ubuntu-24.04
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: ruby/setup-ruby@95ef2b042f9d7a56d8268cba8559e2842e2ad01b # v1
        with:
          ruby-version: '3.4'
          bundler-cache: true
      - name: Rubocop Linter Action
        run: |
          bundle exec rubocop \
            --parallel \
            --fail-level convention \
            --display-only-fail-level-offenses \
            --display-style-guide \
            --force-exclusion \
            --format progress \
            --format github
